---
- name: add the official Sensu repository's key
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present

- name: add the official Sensu repository
  copy:
    src=sensu-server.list
    dest=/etc/apt/sources.list.d/
    backup=yes
  register: aptrepo

- name: refresh apt cache
  apt: update_cache=yes
  when: aptrepo.changed

- name: install sensu
  apt: name=sensu state=present

- name: set which Ruby to use
  lineinfile:
    dest=/etc/default/sensu
    regexp=^EMBEDDED_RUBY=
    line=EMBEDDED_RUBY={{ sensu_server_embedded_ruby }}

- name: set which user to use
  lineinfile:
    dest=/etc/default/sensu
    regexp=^USER=
    line=USER={{ sensu_install_owner }}

- name: create the SSL directory
  file:
    path=/etc/sensu/ssl
    owner=sensu
    group=sensu
    mode=0750
    state=directory

- name: copy the SSL certificate & key
  copy:
    src=files/sensu_{{ item }}.pem
    dest=/etc/sensu/ssl/{{ item }}.pem
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  with_items:
    - client_cert
    - client_key

- name: generate /etc/sensu/config.json
  template:
    src=sensu.config.json.j2
    dest=/etc/sensu/config.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify:
    - restart sensu server
    - restart sensu client
